### ISSUE TITLE
Create new skins

### ISSUE THREAD

**Issue by newtoq** [sputt/wabbitemu#1]
I am trying to make new skins because of bad eye sight. How do you create key map for new skin. I cobbled this together using copy & paste with paint.net.
![ti-81sv2 807x405](https://user-images.githubusercontent.com/24573245/41879883-1c60f660-78a1-11e8-83ad-8edc26aa6bb2.png)
![ti-81sv keymap 807x405](https://user-images.githubusercontent.com/24573245/41879893-2bec77b2-78a1-11e8-9c4f-ac7eac952919.png)
The keys work they dont go dark when you push them. But the window will not change shape with new skin. Using wabbitemu_1.7.2.11. It dosent work in Wabbitemu 1.9.5.20 or 21.

**Comment by sputt** [comment]
Let me see if I can review how it works, it's been a while

**Comment by sputt** [comment]
Thanks for attaching you skin files.  With 1.9.5.22 you should be able to use this

**Comment by sputt** [comment]
@BuckeyeDude We should probably rework the ridiculously complicated skin sizing code...
