### ISSUE TITLE
Improper window sizing on startup

### ISSUE THREAD

**Issue by Jap2-0** [sputt/wabbitemu#28]
Hi,

First, thanks for creating Wabbitemu.  As a student it's been super helpful, and convenient.

I installed Wabbit on a new Windows 10 laptop recently and it is not the correct size at startup (it clips off part of the calculator).  I also tried this with a different skin, with the same issue.  Resizing the window fixes it, but it always starts up at a size taking up the full screen height (despite what I set it to) and with the issue shown below cutting the side off.

![image](https://user-images.githubusercontent.com/40511669/121984189-89f4ac00-cd60-11eb-8f2a-d8b1202beda3.png)

Thanks!

**Comment by IISAKNIFE** [comment]
This is a bug with the latest release, if you download the previous release, this bug does not exist

**Comment by YouwenWang** [comment]
You can click the maximize icon at the top right to see the whole calculator.

**Comment by sputt** [comment]
This will be fixed by #24 - it is a scaling issue
