### ISSUE TITLE
Emulator Doesn't Scale Up with Computer Resolution [4K Screen]

### ISSUE THREAD

**Issue by dragonramer** [sputt/wabbitemu#6]
Please make it so we can scale the calculator more on a 4k display; greatly appreciated. Thanks!

**Comment by SimonEast** [comment]
Maybe it's been fixed since you posted this, but I've been using Wabbitemu on a 4K monitor and the TI-84 Plus looks and works great! I can make it full height of the monitor and it works well.

**Comment by sputt** [comment]
High DPI support will be implemented on #24
